config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :workouts
  resources :users, :only => [:show] do
    resources :personal_bests
  end
  root 'workouts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personal_best.rb
class PersonalBest < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :workouts, dependent: :destroy
  has_many :personal_bests, dependent: :destroy
  
  def how_many?(type)
    eval("workouts.where.not(#{type}: \"\").count")
  end
end

app/models/workout.rb
class Workout < ApplicationRecord
  #validates :date, presence: true
  belongs_to :user
  
  
  def self.search(search)
     if search
        where("weightlifting LIKE ? OR strength LIKE ? OR gymnastics LIKE ? OR wod LIKE ? OR mobility LIKE ? OR other LIKE ?",
        "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
     else
        Workout.all
     end
  end
  
  def display_workout
    t = Array.new
    t << "weightlifting" unless weightlifting.blank?
    t << "strength" unless strength.blank?
    t << "gymnastics" unless gymnastics.blank?
    t << "wod" unless wod.blank?
    t << "mobility" unless mobility.blank?
    t << "other" unless other.blank?
    t.empty? ? "no info about workout" : t.join(", ").to_s
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/personal_bests_controller.rb
class PersonalBestsController < ApplicationController
  
  before_action :find_personal_best, only: [:edit, :update, :destroy]
  
  def new
    @personal_best = current_user.personal_bests.new
  end
  
  def create
    @personal_best = current_user.personal_bests.create(personal_best_params)
    if @personal_best.save
      redirect_to current_user
    else
      render 'new'
    end
  end
  
  def edit
    @personal_best = current_user.personal_bests.find(params[:id])
  end
  
  def update
    if @personal_best.update(personal_best_params)
      redirect_to current_user
    else
      redirect_to current_user
    end
  end
  
  def destroy
    @personal_best.destroy
    redirect_to current_user
  end
  
  private
    
    def personal_best_params
      params.require(:personal_best).permit(:date, :exercise, :score)
    end
    
    def find_personal_best
      @personal_best = current_user.personal_bests.find(params[:id])
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :find_user
  before_action :correct_user?
  
  
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  
    def find_user
       @user = User.find(params[:id])
    end
    
    def correct_user?
      redirect_to root_path if (@user != current_user)
    end
  
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  
  before_action :find_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user?, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @workouts = current_user.workouts.search(params[:search]).order("date DESC").paginate(page: params[:page], per_page: 5)
  end
  
  def show
  end
  
  def new
    @workout = current_user.workouts.new
  end
  
  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      flash[:notice] = "New WOD was created."
      redirect_to root_path
    else
      flash[:notice] = "WOD was not created."
      render 'new'
    end
  end
    
    
    
  def edit
  end
  
  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end
  
  def destroy
    @workout.destroy
    redirect_to root_path
  end
  
  private
    
    def workout_params
      params.require(:workout).permit(:date, :wod, :food, :mood, :weather, 
                                      :strength, :weightlifting, :gymnastics,
                                      :mobility, :other)
    end
    
    def find_workout
      @workout = Workout.find(params[:id])
    end
    
    def correct_user?
      redirect_to root_path if (@workout.user != current_user)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personal_bests_helper.rb
module PersonalBestsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default fixed-top">
  
  
  <%= link_to image_tag("LOGO_WOD5.png"), root_path, class: "nav navbar-nav navbar-left" %>
  <ul class="nav navbar-nav navbar-right">
    
    <% if user_signed_in? %>
      <li><%= form_tag workouts_path, method: :get do %>
            <%= text_field_tag :search, params[:search], placeholder: "Find your WOD" %>
            <button type="submit" class="btn btn-default" >
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </button>
          <% end %>
      </li>
      <li><%= link_to "Your Profile", current_user %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WodLog</title>
    <%= csrf_meta_tags %>

    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag "application", "chartkick" %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800&amp;subset=latin-ext" rel="stylesheet">
  </head>
  <body>
    <div class = "container scrollbar">
      <%= render 'layouts/header' %>
      <p class="notice"><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/personal_bests/_form.html.erb
<%= simple_form_for ([current_user, current_user.personal_bests.build]) do |f| %>
<h3> Add your PR: </h3>
  <table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Exercise</th>
      <th>Score</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= f.input :date, label: false, input_html: { class: 'form-control' } %></td>
      <td><%= f.input :exercise, label: false, input_html: { class: 'form-control' } %></td>
      <td><%= f.input :score, label: false, input_html: { class: 'form-control' } %></td>
      <td><div class = "form-buttons">
          <%= f.button :submit, "Create PR", class:"btn btn-default"%>
          </div>
      </td>
    </tr>
   </tbody>
   </table>
 <% end %>
    

  
  
  

app/views/personal_bests/_personal_bests.html.erb
<% if current_user.personal_bests.any? %>
  <br>
  <h2> Your personal bests: </h2>
  <table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Exercise</th>
      <th>Score</th>
      <th> </th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% current_user.personal_bests.each do |personal_best| %> 
    <tr>
      <td><%= personal_best.date %></td>
      <td><%= personal_best.exercise %></td>
      <td><%= personal_best.score %></td>
      <td><%= link_to "Edit", edit_user_personal_best_path(current_user.id, personal_best), class:"btn btn-default" %></td>
      <td><%= link_to "Delete", user_personal_best_path(current_user.id, personal_best), 
          method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-default" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/personal_bests/edit.html.erb
<%= simple_form_for ([current_user, @personal_best]) do |f| %>
  <h3> Update your PR: </h3>
  <table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Exercise</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= f.input :date, label: false, input_html: { class: 'form-control' } %></td>
      <td><%= f.input :exercise, label: false, input_html: { class: 'form-control' } %></td>
      <td><%= f.input :score, label: false, input_html: { class: 'form-control' } %></td>
    </tr>
   </tbody>
   </table>
 
  <div class = "form-buttons">
    <%= f.button :submit, "Update PR", class:"btn btn-default pull-left"%>
    <%= link_to "Cancel", current_user, class:"btn btn-default pull-right" %>
  </div>
  
<% end %>
    

  
  
  

app/views/users/_pie_chart.html.erb
<%= pie_chart({"Weightlifting" => current_user.how_many?('weightlifting'),
               "strength" => current_user.how_many?('strength'),
               "Gymnastics" => current_user.how_many?('gymnastics'),
               "WOD" => current_user.how_many?('wod'),
               "Mobility" => current_user.how_many?('mobility'),
               "Other" => current_user.how_many?('other')},
               colors: [ '#f9d220', '#7085e5', '#b143c1', '#bc0f09', '#66e291', '#256324'],
               title: "Training type", id: "pie-chart", width: "50%", legend: "none")%>
               
               
               
  

app/views/users/_workout_count.html.erb
<h3><%= case current_user.workouts.count
            when 0 
              "You didn't add any trainings yet."
            when 1
              "You have completed your first training! Way to go!"
            else
              "You've done #{current_user.workouts.count} trainigs. Keep it up!" 
          end %></h3>

app/views/users/shared/_links.html.erb
<div>
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>
</div>

app/views/users/show.html.erb
<%= render 'workout_count' %>
  
  <chart>
  <% if current_user.workouts.any? %>
    <%= line_chart current_user.workouts.group_by_week(:date).count, 
    title: "Trainings per week", id: "count-chart", width: "50%", 
    library: {defaultFontColor: '#d3d3d3'} %>
    <%= render 'pie_chart' %>
  <% end %>
  </chart>
  <div>
  <%= render 'personal_bests/personal_bests' %>
  <%= render 'personal_bests/form' %>
  </div>
  
  
<div><%= link_to "Edit your account info", edit_user_registration_path, 
        class: "btn btn-default btn-block" %></div>

app/views/workouts/_buttons.html.erb
<div class = "buttons">
  
<button type="button" class="btn btn-default" id = "weightliftingButton">
  <span class="glyphicon glyphicon-plus" aria-hidden="true" id = "weightliftingGlyphicon"></span> Weightlifting
</button>

<button type="button" class="btn btn-default" id = "strengthButton">
  <span class="glyphicon glyphicon-plus" aria-hidden="true" id = "strengthGlyphicon"></span> Strength
</button>

<button type="button" class="btn btn-default" id = "gymnasticsButton">
  <span class="glyphicon glyphicon-plus" aria-hidden="true" id = "gymnasticsGlyphicon"></span> Gymanstics
</button>

<button type="button" class="btn btn-default" id = "wodButton">
  <span class="glyphicon glyphicon-plus" aria-hidden="true" id = "wodGlyphicon"></span> WOD
</button>

<button type="button" class="btn btn-default" id = "mobilityButton">
  <span class="glyphicon glyphicon-plus" aria-hidden="true" id = "mobilityGlyphicon"></span> Mobility
</button>

<button type="button" class="btn btn-default" id = "otherButton">
  <span class="glyphicon glyphicon-plus" aria-hidden="true" id = "otherGlyphicon"></span> Other
</button>


</div>

app/views/workouts/_form.html.erb
<h1> NEW WORKOUT </h1>
<br>
<%= simple_form_for @workout do |f| %>
  <table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Mood</th>
      <th>Food</th>
      <th>Weather</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= f.input :date, label: false, input_html: { class: 'form-control' } %></td>
      <td><%= f.input :mood, label: false, placeholder: "You ok?", input_html: { class: 'form-control' } %></td>
      <td><%= f.input :food, label: false, placeholder: "Pizza again?", input_html: { class: 'form-control' } %></td>
      <td><%= f.input :weather, label: false, placeholder: "Sunny enough?", input_html: { class: 'form-control' } %></td>
    </tr>
   </tbody>
   </table>
  <%= render 'buttons' %>
  
    <section>
    <wod id = "weightlifting"><%= f.input :weightlifting, label: "Weightlifting", 
    input_html: { class: 'form-control'} %></wod>
    <wod id = "strength"><%= f.input :strength, label: "Strength", 
    input_html: { class: 'form-control'} %></wod>
    <wod id = "gymnastics"><%= f.input :gymnastics, label: "Gymanstics", 
    input_html: { class: 'form-control'} %></wod>
    <wod id = "wod"><%= f.input :wod, label: "WOD", 
    input_html: { class: 'form-control'} %></wod>
    <wod id = "mobility"><%= f.input :mobility, label: "Mobility", 
    input_html: { class: 'form-control'} %></wod>
    <wod id = "other"><%= f.input :other, label: "Other", 
    input_html: { class: 'form-control'} %></wod>
    </section>
  
  <div class = "form-buttons">
    <%= f.button :submit, class:"btn btn-default pull-left"%>
    <%= link_to "Cancel", root_path, class:"btn btn-default pull-right" %>
  </div>
  
<% end %>

app/views/workouts/_workouts.html.erb
<h2> Workout description:</h2>
<br>
  <table class="table">
  <thead>
    <tr>
      <% unless @workout.weightlifting.blank? %><th>Weightlifting</th><% end %>
      <% unless @workout.strength.blank? %><th>Strength</th><% end %>
      <% unless @workout.gymnastics.blank? %><th>Gymanstics</th><% end %>
      <% unless @workout.wod.blank? %><th>WOD</th><% end %>
      <% unless @workout.mobility.blank? %><th>Mobility</th><% end %>
      <% unless @workout.other.blank? %><th>Other</th><% end %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% unless @workout.weightlifting.blank? %>
        <td><%= simple_format("#{@workout.weightlifting}") %></td>
      <% end %>
      
      <% unless @workout.strength.blank? %>
        <td><%= simple_format("#{@workout.strength}") %></td>
      <% end %>
      
      <% unless @workout.gymnastics.blank? %>
        <td><%= simple_format("#{@workout.gymnastics}") %></td>
      <% end %>
      
      <% unless @workout.wod.blank? %>
        <td><%= simple_format("#{@workout.wod}") %></td>
      <% end %>
      
      <% unless @workout.mobility.blank? %>
        <td><%= simple_format("#{@workout.mobility}") %></td>
      <% end %>
      
      <% unless @workout.other.blank? %>
        <td><%= simple_format("#{@workout.other}") %></td>
      <% end %>
    </tr>
   </tbody>
  </table>

app/views/workouts/edit.html.erb
<h1> Edit Workout </h1>
  <%= render 'form' %>

app/views/workouts/index.html.erb
<p><%= link_to "ADD WOD", new_workout_path, class: "btn btn-default btn-block" %></p>

<div class="list-group middle">  
  
  <% if @workouts.any?%>
  <% @workouts.each do |workout| %>
    <p><%= link_to "#{workout.date.strftime('%A %d.%m.%y')} (#{workout.display_workout})", workout, class: "list-group-item" %></p>
  <% end %>
    <%= will_paginate @workouts if @workouts.any?%>
  <% end %>
</div>

app/views/workouts/new.html.erb
<%= render 'form' %>
  

app/views/workouts/show.html.erb
<h2><%= @workout.date.strftime('%A %d.%m.%y') %></h2>
  <br>
  <table class="table wod-table">
  <thead>
    <tr>
      <th>Mood</th>
      <th>Food</th>
      <th>Weather</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @workout.mood.blank? ? "No info" : @workout.mood %></td>
      <td><%= @workout.food.blank? ? "No info" : @workout.food %></td>
      <td><%= @workout.weather.blank? ? "No info" : @workout.weather %></td>
    </tr>
   </tbody>
   </table>
   
   <%= render 'workouts' %>
   
<div>
  <%= link_to "Back", root_path, class:"btn btn-default" %>
  <%= link_to "Edit", edit_workout_path, class:"btn btn-default" %>
  <%= link_to "Delete", workout_path, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-default" %>
</div>
  